# currently a strange bug when docker-compose build

version: '3.8'
services: 

  frontend:
    depends_on: 
      - opensource-api
    build: ./frontend
    ports:
      - 3000:3000
         
  opensource-api:
    image: bretttolbert/verbecc-svc:latest
    ports:
      - "8000:8000"
    command: ["uvicorn", "verbecc_svc:app", "--host", "0.0.0.0", "--reload", "--port", "8000"]
    # command: ['docker-compose', '-f', 'docker-compose.common.yml', '-f docker-compose.dev.yml', 'up']
    # volumes:
    #   - ./python/:/code